return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    opts = {
        auto_install = true,
        indent = { enable = true },
        highlight = { enable = true },
        ensure_installed = {
            "bash",
            "c",
            "comment",
            "cpp",
            "css",
            "gitignore",
            "html",
            "javascript",
            "json",
            "lua",
            "markdown",
            "markdown_inline",
            "php",
            "printf",
            "python",
            "regex",
            "rust",
            "sql",
            "typescript",
            "vim",
            "yaml",
        },
    },
}
