import = [
    '~/.config/alacritty/keybindings.toml',
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 12 }
opacity = 0.9
title = 'Alacritty'
class = { general = 'Alacritty', instance = 'Alacritty' }

[font]
size = 11
offset = { x = 1, y = 0 }

[font.normal]
family = "M+1Code Nerd Font Mono"
style = "Regular"

[font.bold]
family = "M+1Code Nerd Font Mono"
style = "Bold"
