import = [
    '~/.config/alacritty/keybindings.toml',
    '~/.config/alacritty/tokyodark.toml',
]

[window]
padding = { x = 30, y = 36 }
title = 'Alacritty'
class = { general = 'Alacritty', instance = 'Alacritty' }

[font]
size = 10
offset = { x = 1, y = 0 }

[font.normal]
family = "M+1Code Nerd Font Mono"
style = "Regular"

[font.bold]
family = "M+1Code Nerd Font Mono"
style = "Bold"
