#!/bin/bash

set -eu

function __menu {
    [[ -z $1 ]] && exit 1
    rofi -dmenu -i -p "$@"
}

function __edit_file {
    [[ -f $1 ]] || exit 1
    "${TERM:-alacritty}" -e "${EDITOR:-vim}" "$1"
}

function __is_number {
    for arg in "$@"; do
        case "$arg" in
            ''|*[!0-9]*) return 1 ;;
        esac
    done
    return 0
}

function __max {
    if [[ "$#" != '2' ]]; then
        echo "ERROR: two numbers must be provided!" >&2
        exit 1
    fi
    if ! __is_number $1 $2; then
        echo "ERROR: provided arguments must be of type number!" >&2
        exit 1
    fi
    echo $(( $1 > $2 ? $1 : $2 ))
}

function __min {
    if [[ "$#" != '2' ]]; then
        echo "ERROR: two numbers must be provided!" >&2
        exit 1
    fi
    if ! __is_number $1 $2; then
        echo "ERROR: provided arguments must be of type number!" >&2
        exit 1
    fi
    echo $(( $1 < $2 ? $1 : $2 ))
}

function __cp2cb {
    xclip -r -selection clipboard
}

# https://stackoverflow.com/a/17841619
function __join_by {
    local d=${1-} f=${2-}
    if shift 2; then
        printf %s "$f" "${@/#/$d}"
    fi
}
