#!/bin/bash

function __menu {
    [[ -z $1 ]] && exit 1
    rofi -dmenu -i -p "$@"
}

function __edit_file {
    [[ -f $1 ]] || exit 1
    "${TERM:-alacritty}" -e "${EDITOR:-vim}" "$1"
}

function __cp2cb {
    xclip -r -selection clipboard
}

# https://stackoverflow.com/a/17841619
function __join_by {
    local d=${1-} f=${2-}
    if shift 2; then
        printf %s "$f" "${@/#/$d}"
    fi
}
