#!/bin/bash

set -eu
source __dm_helper

# NOTE: do not surround paths using quotes!
declare -A configs=(
    ['zsh']=~/.zshrc
    ['bash']=~/.bashrc
    ['sh-alias']=~/.config/shell/aliases.sh
    ['sh-env']=~/.config/shell/env.sh
    ['sh-profile']=~/.config/shell/profile.sh
    ['alacritty']=~/.config/alacritty/alacritty.toml
    ['qtile']=~/.config/qtile/config.py
    ['picom']=~/.config/picom/picom.conf
    ['rofi']=~/.config/rofi/config.rasi
    ['nvim']=~/.config/nvim/lua/vim-options.lua
    ['vim']=~/.vimrc
)

names="$(__join_by '\n' "${!configs[@]}")"
choice="$(printf "$names" | __menu 'Config File:')"
[[ -z $choice ]] && exit 1

__edit_file "${configs[$choice]}"
