#!/bin/bash

set -eu
source __dm_helper

choice=$(printf "󰐥 Shutdown\n Restart\n󰤄 Suspend\n Log out"\
    | __menu 'Power Option:' -l 4)

case "$choice" in
    ' Restart')  reboot            ;;
    '󰐥 Shutdown') shutdown    now   ;;
    '󰤄 Suspend')  systemctl suspend ;;
    ' Log out')  killall    qtile  ;;
    *) exit 1 ;;
esac
